export const landData = [
    { name: 'Đất nông nghiệp', code: 'NNP', color: '#ffff64' },
    { name: 'Đất sản xuất nông nghiệp', code: 'SXN', color: '#fffc6e' },
    { name: 'Đất trồng cây hàng năm', code: 'CHN', color: '#fffc78' },
    { name: 'Đất trồng lúa', code: 'LUA', color: '#fffc82' },
    { name: 'Đất chuyên trồng lúa nước', code: 'LUC', color: '#fffc8c' },
    { name: 'Đất trồng lúa nước còn lại', code: 'LUK', color: '#fffc96' },
    { name: 'Đất trồng lúa nương', code: 'LUN', color: '#fffcb4' },
    { name: 'Đất trồng cây hàng năm khác', code: 'HNK', color: '#fff0b4' },
    { name: 'Đất bằng trồng cây hàng năm khác', code: 'BHK', color: '#fff0b4' },
    { name: 'Đất nương rẫy trồng cây hàng năm khác', code: 'NHK', color: '#fff0b4' },
    { name: 'Đất trồng cây lâu năm', code: 'CLN', color: '#ffd2a0' },
    { name: 'Đất lâm nghiệp', code: 'LNP', color: '#aaff32' },
    { name: 'Đất nuôi trồng thủy sản', code: 'NTS', color: '#aaffff' },
    { name: 'Đất làm muối', code: 'LMU', color: '#fffffe' },
    { name: 'Đất nông nghiệp khác', code: 'NKH', color: '#f5ffb4' },
    { name: 'Đất phi nông nghiệp', code: 'PNN', color: '#ffff64' },
    { name: 'Đất ở', code: 'OTC', color: '#ffb4ff' },
    { name: 'Đất ở tại nông thôn', code: 'ONT', color: '#ffd0ff' },
    { name: 'Đất ở tại đô thị', code: 'ODT', color: '#ffa0ff' },
    { name: 'Đất chuyên dùng', code: 'CDG', color: '#ffa0aa' },
    { name: 'Đất xây dựng trụ sở cơ quan', code: 'TSC', color: '#ffaaa0' },
    { name: 'Đất quốc phòng', code: 'CQP', color: '#ff6450' },
    { name: 'Đất an ninh', code: 'CAN', color: '#ff5046' },
    { name: 'Đất xây dựng công trình sự nghiệp', code: 'DSN', color: '#ffa0aa' },
    { name: 'Đất xây dựng trụ sở của tổ chức sự nghiệp', code: 'DTS', color: '#faaaa0' },
    { name: 'Đất xây dựng cơ sở văn hóa', code: 'DVH', color: '#ffaaa0' },
    { name: 'Đất xây dựng cơ sở dịch vụ xã hội', code: 'DXH', color: '#ffaaa0' },
    { name: 'Đất xây dựng cơ sở y tế', code: 'DYT', color: '#ffaaa0' },
    { name: 'Đất xây dựng cơ sở giáo dục và đào tạo', code: 'DGD', color: '#ffaaa0' },
    { name: 'Đất xây dựng cơ sở thể dục thể thao', code: 'DTT', color: '#ffaaa0' },
    { name: 'Đất xây dựng cơ sở khoa học và công nghệ', code: 'DKH', color: '#ffaaa0' },
    { name: 'Đất xây dựng cơ sở ngoại giao', code: 'DNG', color: '#ffaaa0' },
    { name: 'Đất xây dựng công trình sự nghiệp khác', code: 'DSK', color: '#ffaaa0' },
    { name: 'Đất sản xuất, kinh doanh phi nông nghiệp', code: 'CSK', color: '#ffa0aa' },
    { name: 'Đất khu công nghiệp', code: 'SKK', color: '#faaaa0' },
    { name: 'Đất cụm công nghiệp', code: 'SKN', color: '#faaaa0' },
    { name: 'Đất khu chế xuất', code: 'SKT', color: '#faaaa0' },
    { name: 'Đất thương mại, dịch vụ', code: 'TMD', color: '#faaaa0' },
    { name: 'Đất cơ sở sản xuất phi nông nghiệp', code: 'SKC', color: '#faaaa0' },
    { name: 'Đất sử dụng cho hoạt động khoáng sản', code: 'SKS', color: '#cdaacd' },
    { name: 'Đất sản xuất vật liệu xây dựng, làm đồ gốm', code: 'SKX', color: '#cdaacd' },
    { name: 'Đất có mục đích công cộng', code: 'CCC', color: '#ffaaa0' },
    { name: 'Đất giao thông', code: 'DGT', color: '#ffaa32' },
    { name: 'Đất thủy lợi', code: 'DTL', color: '#aaffff' },
    { name: 'Đất có di tích lịch sử - văn hóa', code: 'DDT', color: '#ffaaa0' },
    { name: 'Đất danh lam thắng cảnh', code: 'DDL', color: '#ffaaa0' },
    { name: 'Đất sinh hoạt cộng đồng', code: 'DSH', color: '#ffaaa0' },
    { name: 'Đất khu vui chơi, giải trí công cộng', code: 'DKV', color: '#ffaaa0' },
    { name: 'Đất công trình năng lượng', code: 'DNL', color: '#ffaaa0' },
    { name: 'Đất công trình bưu chính viễn thông', code: 'DBV', color: '#ffaaa0' },
    { name: 'Đất chợ', code: 'DCH', color: '#ffaaa0' },
    { name: 'Đất bãi thải, xử lý chất thải', code: 'DRA', color: '#cdaacd' },
    { name: 'Đất công trình công cộng khác', code: 'DCK', color: '#ffaaa0' },
    { name: 'Đất cơ sở tôn giáo', code: 'TON', color: '#ffaaa0' },
    { name: 'Đất cơ sở tín ngưỡng', code: 'TIN', color: '#ffaaa0' },
    { name: 'Đất nghĩa trang, nghĩa địa, nhà tang lễ, nhà hỏa táng', code: 'NTD', color: '#d2d2d2' },
    { name: 'Đất sông, ngòi, kênh, rạch, suối', code: 'SON', color: '#a0ffff' },
    { name: 'Đất có mặt nước chuyên dùng', code: 'MNC', color: '#b4ffff' },
    { name: 'Đất phi nông nghiệp khác', code: 'PNK', color: '#ffaaa0' },
    { name: 'Đất chưa sử dụng', code: 'CSD', color: '#fffffe' },
    { name: 'Đất có mặt nước ven biển (chỉ tiêu quan sát)', code: 'MVB', color: '#b4ffff' },
];
